export const parentCategories = [
  "Clothes",
  "Fashion",
  "Technology",
  "Outdoor & Adventure",
  "Baby & Kids",
  "Party & Events",
  "Hobbies & Collectibles",
  "Fitness & Activewear",
  "Tech Accessories",
  "Ethnic & Cultural",
  "Home Improvement",
  "Garden & Outdoor Living",
  "Luxury & High-End",
  "Tech Wearables",
  "Educational Products",
  "Subscription Boxes - Specialty",
  "Fashion Accessories",
  "Artisanal & Handcrafted",
  "Sustainable Living",
  "Smart Home Automation",
  "Corporate Gifts",
  "Emergency & Safety",
  "Self-Care & Relaxation",
  "Virtual Events & Experiences",
  "Art Supplies & Craft Kits",
];
