version: "3.8"
services:
  nextjs:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - nestjs

  nestjs:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
